name: dotlottie_flutter
description: "dotLottie for Flutter."
version: 0.0.4
homepage: "https://lottiefiles.com"
repository: "https://github.com/lottiefiles/dotlottie-flutter"

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.lottiefiles.dotlottie_flutter
        pluginClass: DotLottieFlutterPlugin
      ios:
        pluginClass: DotLottieFlutterPlugin
      macos:
        pluginClass: DotLottieFlutterPlugin
      web:
        pluginClass: DotLottieFlutterWeb
        fileName: dotlottie_flutter_web.dart
